### PR TITLE
Various tweaks and updates - Drops support for Tedious<8.3.0 though.

### PR DESCRIPTION
**Pull request by Nedlinin**
## Description
Begins migration to a promise-based approach.

Updates tests from 8/16 passing to 16/16 passing.

Use peerDependency to allow a user to bring whatever version of Tedious they want to bring with them (assuming >=8.3.0) rather than forcing an install of an internal version and allowing an "override" using the overrideTedious function previously used.

Signed-off-by: Chris Heath <cheath@spectrumsi.com>

## Motivation and Context
Bringing codebase up to slightly more modern standards.  Allows easier overriding of the Tedious version and simpler maintenance.  Lastly, brings the tests back up to proper form.

## How Has This Been Tested?
This runs in my companies internal tooling and some customer facing products.  Mostly tweaks I've been collecting over time as Tedious updates.

## Types of changes
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by 700software** [comment]
I'm largely going off your word for this having been tested.

Code looks alright to me. Since there are major code changes, I want to leave this PR open a few weeks before cutting this to version 2.1.

Anyone having other changes they want represented in this version should let me know.

Any known breaking change besides upping the min tedious version to 8.3?

**Comment by 700software** [comment]
I'm really good with merge conflicts if anything comes up later.

**Review by 700software — APPROVED** [review]

**Comment by Nedlinin** [comment]
So the breaking changes:

If anyone uses the old callback method for the drain function they have to switch to awaiting a promise.

End users need to specifically install a tedious package >=8.3.0 rather than relying on one being packaged with this lib directly.

Because it is using async/await in places you need a Node version capable of running it. (I believe that is Node 7.6 by default).  Could refactor it slightly if we really care about versions that far back..

**Comment by Nedlinin** [comment]
Added a quick commit to update the README to reflect the proper Tedious connection config object these days.

**Comment by 700software** [comment]
This is good. I'm cutting this to version 2.1 soon.

**Comment by spreadred** [comment]
@700software is this going to be merged in, or is this fork also dead?

**Comment by 700software** [comment]
Yeah I can merge it

**Review by 700software — APPROVED** [review]

**Comment by 700software** [comment]
@Nedlinin, @kaptainkommie, The update is published.
Honestly wow that was a lot easier than I expected.

Latest can be installed with `npm install tedious-connection-pool2@latest`
👆🏻 Guys please try doing this and let me know if it's working.
I have no testing environment for this anymore.

@Nedlinin, I'm willing to give you access to the npm account. Publishing updates is really easy actually. I'm also willing to do the publish step no problem.

**Comment by 700software** [comment]
faster next time

**Comment by spreadred** [comment]
@700software Thanks for merging. I'll give it some testing sometime this week and let you know. If you wanted to automate the publishing to NPM, without providing access/credentials to someone else, You could setup Github Actions such that after a PR is merged into `master` branch, it packages and publishes it to the NPM registry.

**Pull request merged**
